### PR TITLE
Merge all the modules together

### PR DESCRIPTION
**Pull request by ForNeVeR**
This will allow us to rely on IDEA artifacts instead of our own.

Changes in this PR:
- Fix a couple of test failures discovered after module merge (not all tests were hygienic enough)
- Fix a test in `UrlHelperTest` class that was broken after plugin name migration
- Drop `tfsIntegration` directory that was unused
- Clean up the dependencies section

### CODE REVIEW

**Comment by ForNeVeR** [comment]
Pls wait, will investigate CI failures

**Comment by ForNeVeR** [comment]
Ready!

**Comment by mfilippov** [comment]
@ForNeVeR Please resolve conflicts.

**Comment by ForNeVeR** [comment]
Already on it.

**Comment by ForNeVeR** [comment]
Rebased on top of `master`.

**Pull request merged**
