### PR TITLE
Fix L2 tests, update README.md

### PR DESCRIPTION
**Pull request by mfilippov**
After this PR L2Tests could be running from Gradle and IDEA. I think right now this test doesn't work on CI because tests are broken.

### CODE REVIEW

**Comment by mfilippov** [comment]
@kaylangan PR is ready for review.

**Comment by mfilippov** [comment]
@kaylangan ping

**Comment by mfilippov** [comment]
@jrbriggs @jeschu1 @kaylangan Any news?

**Comment by kaylangan** [comment]
@ForNeVeR can you review this PR?

**Comment by ForNeVeR** [comment]
Will do!

**Pull request merged**
